baseURL: https://sudheer.github.io/
title: SuDo
pagination:
  pagerSize: 10

enableRobotsTXT: true

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
menu:
  main:
    - weight: 1
      name: ğŸ“ Posts
      url: /categories/posts/
    - weight: 2
      name: ğŸ’¬ Micro
      url: /categories/micro/
    - weight: 5
      name: ğŸ‘¤ About
      url: /about/

params:
  DateFormat: 01/02/2006
  defaultTheme: auto
  UseHugoToc: true
  showtoc: true
  tocopen: false
  homeInfoParams:
    Title: Hello! ğŸ‘‹
    Content:
      ğŸ’¡This space is where I share my â€˜Today I Learnedâ€™ moments and other
      explorations in tech, life, and beyond.
markup:
  goldmark:
    renderer:
      unsafe: true
